spring:
  datasource:
    url: jdbc:hsqldb:file:db/cs_db
    username: admin
    password: admin
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create # made with purpose
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
